"""Added new fields to campaigns and contributions

Revision ID: caef24f22773
Revises: 72842c63f1d8
Create Date: 2025-04-10 05:55:25.390703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caef24f22773'
down_revision: Union[str, None] = '72842c63f1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('bucket_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_campaigns_bucket_name'), 'campaigns', ['bucket_name'], unique=False)
    op.add_column('contributions', sa.Column('file_name_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_contributions_data_url'), 'contributions', ['data_url'], unique=False)
    op.create_index(op.f('ix_contributions_file_name_url'), 'contributions', ['file_name_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributions_file_name_url'), table_name='contributions')
    op.drop_index(op.f('ix_contributions_data_url'), table_name='contributions')
    op.drop_column('contributions', 'file_name_url')
    op.drop_index(op.f('ix_campaigns_bucket_name'), table_name='campaigns')
    op.drop_column('campaigns', 'bucket_name')
    # ### end Alembic commands ###
